title: Daniel Gouvêa
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  .
baseurl: "" # the subpath of your site, e.g. /blog
url: http://danielgouvea.com
# twitter_username: jekyllrb
github_username: danielgouvea

# https://github.com/jekyll/minima/tree/v2.5.1
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark

header_pages:
#  - about.md
#  - portfolio.md

google_analytics: UA-162111447-1
